common: &common
development:
  <<: *common
  track_data_images_dir: <%= File.join(Rails.root , '/public/images/track_data_images') %>
test:
  <<: *common
  track_data_images_dir: <%= File.join(Rails.root , '/test/fixtures/files/track_data_images') %>
production:
